
-- Nome dos Integrantes: 
-- Claudio Silva Bispo RM553472
-- Patricia Naomi Yamagishi RM552981

-- Deletar tabelas caso já existam

DROP TABLE Cliente CASCADE CONSTRAINTS;
DROP TABLE Clinica CASCADE CONSTRAINTS;
DROP TABLE Dentista CASCADE CONSTRAINTS;

-- Criação das Tabelas

-- Tabela Cliente 
CREATE TABLE Cliente ( 
    id_cliente INTEGER GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) NOT NULL PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL, 
    sobrenome VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) CONSTRAINT email_unique UNIQUE NOT NULL, 
    telefone VARCHAR2(15) NOT NULL, 
    data_nasc DATE NOT NULL, 
    endereco VARCHAR2(255) NOT NULL
); 

-- Tabela Clínica 
CREATE TABLE Clinica ( 
    id_clinica INTEGER GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) NOT NULL PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL, 
    endereco VARCHAR2(255) NOT NULL, 
    telefone VARCHAR2(15) NOT NULL, 
    avaliacao DECIMAL(2, 1) NOT NULL,
    preco_medio DECIMAL(10, 2) NOT NULL
); 

-- Tabela Dentista
CREATE TABLE Dentista (
    id_dentista INTEGER GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) NOT NULL PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    sobrenome VARCHAR2(100) NOT NULL,
    telefone VARCHAR2(15) NOT NULL,
    id_clinica INTEGER NOT NULL,
    id_especialidade INTEGER NOT NULL,
    avaliacao DECIMAL(2, 1) NOT NULL,
    
    CONSTRAINT fk_dentista_clinica FOREIGN KEY (id_clinica) REFERENCES Clinica(id_clinica),
    CONSTRAINT fk_dentista_especialidade FOREIGN KEY (id_especialidade) REFERENCES Especialidade(id_especialidade)
);

SET SERVEROUTPUT ON;

-- Package Body para a tabela CLIENTE
CREATE OR REPLACE PACKAGE BODY PKG_CLIENTES AS 

    -- Procedure para inserir um cliente
    PROCEDURE INSERIR_CLIENTE(P_NOME IN VARCHAR2, P_SOBRENOME IN VARCHAR2, P_EMAIL IN VARCHAR2, P_TELEFONE IN VARCHAR2, P_DATA_NASCIMENTO IN DATE, P_ENDERECO IN VARCHAR2) IS
    BEGIN
        INSERT INTO "RM553472"."CLIENTE" ("NOME", "SOBRENOME", "EMAIL", "TELEFONE", "DATA_NASC", "ENDERECO") 
        VALUES (P_NOME, P_SOBRENOME, P_EMAIL, P_TELEFONE, P_DATA_NASCIMENTO, P_ENDERECO);
        
        COMMIT;
    END INSERIR_CLIENTE;

    -- Procedure para atualizar um cliente
    PROCEDURE ATUALIZAR_CLIENTE(P_ID IN NUMBER, P_NOME IN VARCHAR2, P_SOBRENOME IN VARCHAR2, P_EMAIL IN VARCHAR2, P_TELEFONE IN VARCHAR2, P_DATA_NASCIMENTO IN DATE, P_ENDERECO IN VARCHAR2) IS
    BEGIN
        UPDATE "RM553472"."CLIENTE"
        SET "NOME" = P_NOME, "SOBRENOME" = P_SOBRENOME, "EMAIL" = P_EMAIL, "TELEFONE" = P_TELEFONE, "DATA_NASC" = P_DATA_NASCIMENTO, "ENDERECO" = P_ENDERECO
        WHERE "ID_CLIENTE" = P_ID;
        
        COMMIT;
    END ATUALIZAR_CLIENTE;
    
    -- Buscar os dados de um cliente
    PROCEDURE buscar_cliente(
        p_id IN NUMBER,
        p_cursor OUT SYS_REFCURSOR
    ) AS
    BEGIN
        OPEN p_cursor FOR 
        SELECT nome, email, telefone FROM Cliente WHERE id_cliente = p_id;
    END buscar_cliente;


    -- Procedure para excluir um cliente
    PROCEDURE EXCLUIR_CLIENTE(P_ID IN NUMBER) IS
    BEGIN
        DELETE FROM "RM553472"."CLIENTE" WHERE "ID_CLIENTE" = P_ID;
        
        COMMIT;
    END EXCLUIR_CLIENTE;

    -- Procedure para listar clientes (retorna um cursor para ser consumido pela aplicação)
    PROCEDURE LISTAR_CLIENTES(P_CURSOR OUT SYS_REFCURSOR) IS
    BEGIN
        OPEN P_CURSOR FOR 
            SELECT "ID_CLIENTE", "NOME", "SOBRENOME", "EMAIL", "TELEFONE", "DATA_NASC", "ENDERECO" 
            FROM "RM553472"."CLIENTE";
    END LISTAR_CLIENTES;
    
    -- Procedure para consultar um cliente por ID
    PROCEDURE PESQUISAR_CLIENTE(P_ID IN NUMBER) IS
    BEGIN
        DELETE FROM "RM553472"."CLIENTE" WHERE "ID_CLIENTE" = P_ID;
        
        COMMIT;
    END PESQUISAR_CLIENTE;

END PKG_CLIENTES;



-- Verifique se a procedure está dentro do pacote
SELECT object_name, object_type, status
FROM user_objects
WHERE object_type = 'PROCEDURE' AND object_name = 'CONSULTAR_CLIENTE_POR_ID';


-- Package Body para a tabela CLINICA
CREATE OR REPLACE PACKAGE BODY pkg_clinica AS 

    PROCEDURE INSERIR_CLINICA(P_NOME IN VARCHAR2, P_ENDERECO IN VARCHAR2, P_TELEFONE IN VARCHAR2, P_AVALIACAO IN DECIMAL, P_PRECO_MEDIO IN DECIMAL) IS
    BEGIN
        INSERT INTO "RM553472"."CLINICA" ("NOME", "ENDERECO", "TELEFONE", "AVALIACAO", "PRECO_MEDIO") 
        VALUES (P_NOME, P_ENDERECO, P_TELEFONE, P_AVALIACAO, P_PRECO_MEDIO);
        
        COMMIT;
    END INSERIR_CLINICA;

    PROCEDURE ATUALIZAR_CLINICA(P_ID IN NUMBER, P_NOME IN VARCHAR2, P_ENDERECO IN VARCHAR2, P_TELEFONE IN VARCHAR2, P_AVALIACAO IN DECIMAL, P_PRECO_MEDIO IN DECIMAL) IS
    BEGIN
        UPDATE "RM553472"."CLINICA"
        SET "NOME" = P_NOME, "ENDERECO" = P_ENDERECO, "TELEFONE" = P_TELEFONE, "AVALIACAO" = P_AVALIACAO, "PRECO_MEDIO" = P_PRECO_MEDIO
        WHERE "ID_CLINICA" = P_ID;
        
        COMMIT;
    END ATUALIZAR_CLINICA;

    PROCEDURE EXCLUIR_CLINICA(P_ID IN NUMBER) IS
    BEGIN
        DELETE FROM "RM553472"."CLINICA" WHERE "ID_CLINICA" = P_ID;
        
        COMMIT;
    END EXCLUIR_CLINICA;

    PROCEDURE LISTAR_CLINICAS(P_CURSOR OUT SYS_REFCURSOR) IS
    BEGIN
        OPEN P_CURSOR FOR 
            SELECT "ID_CLINICA", "NOME", "ENDERECO", "TELEFONE", "AVALIACAO", "PRECO_MEDIO" 
            FROM "RM553472"."CLINICA";
    END LISTAR_CLINICAS;

END pkg_clinica;

-- Criação do Pacote pkg_dentista
CREATE OR REPLACE PACKAGE pkg_dentista AS 
    PROCEDURE INSERIR_DENTISTA(P_NOME IN VARCHAR2, P_SOBRENOME IN VARCHAR2, P_TELEFONE IN VARCHAR2, P_ID_CLINICA IN NUMBER, P_ID_ESPECIALIDADE IN NUMBER, P_AVALIACAO IN DECIMAL);
    PROCEDURE ATUALIZAR_DENTISTA(P_ID IN NUMBER, P_NOME IN VARCHAR2, P_SOBRENOME IN VARCHAR2, P_TELEFONE IN VARCHAR2, P_ID_CLINICA IN NUMBER, P_ID_ESPECIALIDADE IN NUMBER, P_AVALIACAO IN DECIMAL);
    PROCEDURE EXCLUIR_DENTISTA(P_ID IN NUMBER);
    PROCEDURE LISTAR_DENTISTAS(P_CURSOR OUT SYS_REFCURSOR);
END pkg_dentista;

-- Package Body para a tabela DENTISTA
CREATE OR REPLACE PACKAGE BODY pkg_dentista AS 

    PROCEDURE INSERIR_DENTISTA(P_NOME IN VARCHAR2, P_SOBRENOME IN VARCHAR2, P_TELEFONE IN VARCHAR2, P_ID_CLINICA IN NUMBER, P_ID_ESPECIALIDADE IN NUMBER, P_AVALIACAO IN DECIMAL) IS
    BEGIN
        INSERT INTO "RM553472"."DENTISTA" ("NOME", "SOBRENOME", "TELEFONE", "ID_CLINICA", "ID_ESPECIALIDADE", "AVALIACAO")
        VALUES (P_NOME, P_SOBRENOME, P_TELEFONE, P_ID_CLINICA, P_ID_ESPECIALIDADE, P_AVALIACAO);
        
        COMMIT;
    END INSERIR_DENTISTA;

    PROCEDURE ATUALIZAR_DENTISTA(P_ID IN NUMBER, P_NOME IN VARCHAR2, P_SOBRENOME IN VARCHAR2, P_TELEFONE IN VARCHAR2, P_ID_CLINICA IN NUMBER, P_ID_ESPECIALIDADE IN NUMBER, P_AVALIACAO IN DECIMAL) IS
    BEGIN
        UPDATE "RM553472"."DENTISTA"
        SET "NOME" = P_NOME, "SOBRENOME" = P_SOBRENOME, "TELEFONE" = P_TELEFONE, "ID_CLINICA" = P_ID_CLINICA, "ID_ESPECIALIDADE" = P_ID_ESPECIALIDADE, "AVALIACAO" = P_AVALIACAO
        WHERE "ID_DENTISTA" = P_ID;
        
        COMMIT;
    END ATUALIZAR_DENTISTA;

    PROCEDURE EXCLUIR_DENTISTA(P_ID IN NUMBER) IS
    BEGIN
        DELETE FROM "RM553472"."DENTISTA" WHERE "ID_DENTISTA" = P_ID;
        
        COMMIT;
    END EXCLUIR_DENTISTA;

    PROCEDURE LISTAR_DENTISTAS(P_CURSOR OUT SYS_REFCURSOR) IS
    BEGIN
        OPEN P_CURSOR FOR 
            SELECT "ID_DENTISTA", "NOME", "SOBRENOME", "TELEFONE", "ID_CLINICA", "ID_ESPECIALIDADE", "AVALIACAO" 
            FROM "RM553472"."DENTISTA";
    END LISTAR_DENTISTAS;

END pkg_dentista;

SELECT * FROM "RM553472"."CLIENTE";
SELECT * FROM "RM553472"."CLINICA";
SELECT * FROM "RM553472"."DENTISTA";


-- Executar a procedure Pesquisar um cliente
SET SERVEROUTPUT ON;
BEGIN
    pkg_clientes.pesquisar_cliente(p_id => 14);
END;